"""Added photo field as LargeBinary

Revision ID: 08149bfce55f
Revises: e253cc86476b
Create Date: 2025-02-04 17:00:13.269380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08149bfce55f'
down_revision = 'e253cc86476b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
