"""Remove photo field

Revision ID: 94709581bcb6
Revises: 08149bfce55f
Create Date: 2025-02-04 17:15:48.839968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94709581bcb6'
down_revision = '08149bfce55f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
