"""Add photo field to User

Revision ID: e253cc86476b
Revises: f813d2996c26
Create Date: 2025-02-02 22:07:27.023303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e253cc86476b'
down_revision = 'f813d2996c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_image')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.BLOB(), nullable=True))
        batch_op.drop_column('photo')

    op.create_table('user_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.BLOB(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
